	<p><font color="#e89a45">Awareness of Roots in Chinese Culture presents</font></p>

	<div class="header">ONE NIGHT IN BEIJING</div>
    <div class="subheader">Windows Through Time</div>
    
    <p class="date"><em>Saturday, April 26th</em>
    <br><font color="#e89a45">UC Rangos @ 7:30 pm</font></p>
    
    <p>&nbsp;
    <br>Come and enjoy an evening of Chinese cultural performances, including dancing, singing, 
    	and a fashion show featuring both traditional and contemporary Chinese clothing. Learn 
        more about Chinese traditions, and enjoy snacks provided by other Asian organizations 
        on campus.</p>
    
    <p>&nbsp;
	<br>Tickets are <b>$5</b> in advance and <b>$8</b> at the door.
    <br>Reserve your tickets online now and pick them up at the door 
    	at the presale price!<br>
	<form name="tickets" action="closed.php" method="post"><table border="0" cellspacing="0">
	<tr><td>Name<br/><input type="text" id="Name" name="Name" size="30" 
		maxlength="30" class="form"/></td></tr>
	<tr><td>Andrew ID (CMU students only)<br/><input type="text" id="AndrewID"
		name="AndrewID" size="30" maxlength="8" class="form"/></td></tr>
	<tr><td>Preferred e-mail address<br/><input type="text" id="E-mail" name="E-mail" size="30" 
		maxlength="30" class="form"/></td></tr>
	<tr><td>Phone number<br/><input type="text" id="Phone" name="Phone" size="30" 
		maxlength="10" class="form"/></td></tr>
	<tr><td valign="middle">Number of Tickets &nbsp;<select id="Tickets" name="Tickets" size="1"
    	class="form">
		<option value="1">1</option>
		<option value="2">2</option>
		<option value="3">3</option>
		<option value="4">4</option>
		<option value="5">5</option>
		<option value="6">6</option>
		<option value="7">7</option>
		<option value="8">8</option>
	</select></td></tr>
	<tr><td><input type="Submit" id="Submit" name="Submit" value="Submit" 
		class="form"></td></tr>
	</table></form>
    
    <p>&nbsp;</p>
    <p><b>Questions,</b> comments or concerns?
    <br>E-mail <a href="mailto:kqc@andrew.cmu.edu">kqc@andrew.cmu.edu</a>
    <p><a href="http://www.cmuarcc.com" target="_blank">
    	<img src="images/logo-white.png" width="195" height="95" border="0"></a></p>