<html>
<head>
<title>ONE NIGHT IN BEIJING 2008 : Windows Through Time</title>

<style type="text/css">
body
{
	background: #c15016 url('images/bg.jpg') repeat-x;
	color: #FFFFFF;
	margin: 0 0 0 0;
	padding: 0 0 0 0;
	text-align: right;
}
body, tr, td
{
	font-family: Geneva, Helvetica, Arial, sans-serif;
	font-size: 11px;
}
tr, td
{
	color: #fce8b1;
	text-align: left;
}
a
{
	text-decoration: none;
	font-weight: bold;
	color: #e89a45;
}
em
{
	font-style: normal;
	font-weight: bold;
}

.header
{
	font-weight: bold;
	color: #FFFFFF;
	text-transform: uppercase;
	font-size: 26px;
}
.subheader
{
	font-weight: bold;
	color: #e89a45;
	text-transform: capitalize;
	font-size: 20px;	
}
.date
{
	font-size: 14px;
}
.form
{
	background-color: #1a0605;
	font-size: 10px;
	color: #FFFFFF;
	border: 1px solid #c04f17;
}


#container
{
	z-index: 50;
	width: 800px;
	height: 700px;
	position: absolute;
	right: 0;
	bottom: 0;
	text-align: right;
	overflow: auto;
}
#background
{
	z-index: 1;
	position: absolute;
	right: 0;
	bottom: 0;
	vertical-align: bottom;
	text-align: right;
}
#content
{
	width: 300px;
	height: 695px;
	vertical-align: middle;
	z-index: 48;
	position: absolute;
	right: 470;
	bottom: 5;
	text-align: left;
}
</style>
</head>

<body>

<div id="container">
<div id="content">