<html>

<head>

<title>One Night in Beijing 2009: {Awakening}</title>

<style type="text/css">

a { text-decoration:none; color: #FAB389}
a:hover { text-decoration: underline; color:#FAB389}
	
<!--

body {
scrollbar-face-color:#6C5675;
scrollbar-highlight-color:white;
scrollbar-3dlight-color:white;
scrollbar-darkshadow-color:white;
scrollbar-shadow-color:white;
scrollbar-arrow-color:white;
scrollbar-track-color:#6C5675;
}
-->

</style>

</head>

<body bgcolor=#6C5675 text=white background=bg.gif>

<img src=image.jpg style="position:absolute; top:0px; left:23px; border:0px;" usemap=#map>

<map name=map>
<area shape=rect coords="7,913,68,940" href=index.php alt=Home>
<area shape=rect coords="75,913,137,940" href="index.php?x=about#content" alt=About>
<area shape=rect coords="144,913,224,940" href=index.php?x=reserve#content alt=Reserve>
<area shape=rect coords="231,913,303,940" href=index.php?x=photos#content alt=Photos>
<area shape=rect coords="309,913,379,940" href=index.php?x=videos#content alt=Videos>
<area shape=rect coords="386,913,491,940" href=index.php?x=directions#content alt=Directions>
<area shape=rect coords="498,913,579,940" href=index.php?x=contact#content alt=Contact>
</map>

<a name="content"></a>

<div style="position:absolute; top:942px; left:36px; border:0px; width:561px">

<p align=justify>