</td>

<td style="background-color: white; width:14px;"></td>

</tr>

<tr>

<td style="background-color: white; width:14px;"></td>

<td  class="bottom" style="background-color: white; background-repeat: no-repeat; background-position: bottom; padding: 10px;">

<hr>

<center>
<a href=http://www.cmuarcc.com target=new><img src=small_logo.png style="border: 0px;"></a>
<br>
Design by Robin Chen
<br>
Webmaster: Allison Ko (asko@andrew.cmu.edu)
</center>

</td>

<td style="background-color: white; width:14px;"></td>

</tr>

<td style="background-image: url('corner3.png'); background-repeat: no-repeat; background-position: top left; width: 14px; height: 15px;"></td>
<td style="background-color: white; height: 15px;"></td>
<td style="background-image: url('corner4.png'); background-repeat: no-repeat; background-position: top right; width:14px; height: 15px;"></td>

</table>