<html>

<head>

<title>One Night in Beijing: The Last Scholar</title>

<link rel="icon" type="image/x-ico" href="http://www.cmuarcc.com/favicon.gif" />
<link rel="shortcut icon" type="image/x-icon" href="http://www.cmuarcc.com/favicon.gif" />
<link rel="stylesheet" type="text/css" href="http://www.cmuarcc.com/onib/onibstylesheet.css" />

</head>

<body>

<center>

<table class="top" cellspacing=0>

<tr>
<td height=196 width=326></td>

<td height=196 width=379>

<center>

<img src="http://www.cmuarcc.com/rotate.php" alt="ARCC"  width=341 height=152/>

<br><br>

<a href=index.php>Home</a> | <a href=index.php?x=about>About Us</a> | <a href=index.php?x=reserve>Reserve</a> | <a href=index.php?x=photos>Photos</a> | <a href=index.php?x=videos>Videos</a> | <a href=index.php?x=directions>Directions</a> | <a href=index.php?x=contact>Contact</a><br><br></center>

</td>

<td height=196 width=120></td>
</tr>

</table>

<br><br>

<table class="main" cellspacing=0 cellpadding=0 style="background-color: transparent;">

<tr>

<td style="background-image: url('corner1.png'); background-repeat: no-repeat; background-position: top left; width: 14px; height: 15px;"></td>
<td style="background-color: white; height: 15px;"></td>
<td style="background-image: url('corner2.png'); background-repeat: no-repeat; background-position: top right; width:14px; height: 15px;"></td>

</tr>

<tr>

<td style="background-color: white; width:14px;"></td>

<td style="background-color: white;">

<div class="content">

